name: test_on_push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: javaApiTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run api tests
        run: mvn clean test

