name: test_on_push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: automation UI testsTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Verify Java version
        run: java -version

      - name: Verify Maven installation
        run: mvn -version

      - name: Copy configuration files
        run: |
          mkdir -p src/main/java/testdata
          echo 'key1=value1' > src/main/java/testdata/testdata.properties
          mkdir -p src/main/java/config
          echo 'key2=value2' > src/main/java/config/config.properties

      - name: Run automation UI tests
        run: mvn clean test

